// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3wqomTtvCCOJ3jmJFsXld_DTPLnLfyvQ',
    appId: '1:196489642903:web:64849a5f0c012d76853ad2',
    messagingSenderId: '196489642903',
    projectId: 'katil-app-da774',
    authDomain: 'katil-app-da774.firebaseapp.com',
    storageBucket: 'katil-app-da774.appspot.com',
    measurementId: 'G-8MWJPF0TXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_2GKpyW_vf_phwRTE-pZdk-lXKVkIe24',
    appId: '1:196489642903:android:6ab7e8cafff4c615853ad2',
    messagingSenderId: '196489642903',
    projectId: 'katil-app-da774',
    storageBucket: 'katil-app-da774.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYvLxpnEilyWDQt3Nfqyjn85OgbnfzHiY',
    appId: '1:196489642903:ios:f0d95c1d7d7c3f58853ad2',
    messagingSenderId: '196489642903',
    projectId: 'katil-app-da774',
    storageBucket: 'katil-app-da774.appspot.com',
    iosClientId: '196489642903-209op72nt3pcq26af2pq2912vt0c4cif.apps.googleusercontent.com',
    iosBundleId: 'com.example.bootcampApp1',
  );
}
